[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "https://sapphire-selective-chocolate.glitch.me/api/:splat"
#to = "https://pandapulse.netlify.app/api/:splat"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
